### ISSUE TITLE
improvement : acceleration of the database

### ISSUE THREAD

**Issue by mredstone6** [Tran-Antoine/sphinx#32]
# Idea of improvement for the database

## Research optimization and indexation
Update the database file in the following ways:
* each entries as a different size
* add an indexTable at the start of the database that contains the argument
    * each entry of the indexed table is of the following forms : `numberEntry` `sizePara1` `Para1` `Pointer1` .... `sizeParaN` `ParaN` `PointerN`
    * file not loaded until required (lazy evaluation of files)
 
## Optimization size
* Compression algorithm

## Support for adding information directly to the database 
* Adding support for adding information directly to the database without adding the `trackedFile` corresponding
* Done by using a special CheckSum function that specify that the file doesn't exists and __therefore the information cannot be updated__
* Enable the user to modify the information of the database and regenerate the corresponding file if required

## Code cleanup
* create a new database package

**Comment by Tran-Antoine** [comment]
Since we're not planning on working on this for now, I believe we can close the issue and re-open it if needed
